### ISSUE TITLE
Drop requirement that EnsembleModel have 2 models

### ISSUE THREAD

**Issue by teubert** [nasa/progpy#11]
**Requirement Text**
Ensemble model shall allow creation with one model

**Background Information**
in v1.5, EnsembleModel artificially rejected creation with <2 models

**Suggested Solution**
Remove check 

**Note**
Suggestion from v1.5 release review

**DoD**
 - [ ] Implement feature
 - [ ] Add to tests

**Comment by Ashwani132003** [comment]
Hi, I had resolved this, now ensemble model will raise error only if 0 models are passed.

Here are the screenshots for changes made by me: 
1) in ensemble_model.py at line 38-39
![image](https://github.com/nasa/progpy/assets/76273539/e2c7d10f-6c4e-4644-ab6b-97c7757072e2)
2)in test_ensemble.py at lines 30-33
![image](https://github.com/nasa/progpy/assets/76273539/1283f1ec-ce62-4385-911d-1840521775d7)

tests are passing. Raising error when 0 models are passed.


This is going to be my first contribution to any of Nasa's repos. I want to ask if there is something additional needs to be done from my side before creating the pr? and where should i create the pr, in this repo itself or in nasa/prog_models ? 
waiting for your reply thanks .

**Comment by teubert** [comment]
Hello @Ashwani132003,

Great to meet you and thank you for your interest in contributing to ProgPy. Before we can accept any contributions, you do need to complete a contributors license agreement here: https://github.com/nasa/progpy/tree/master/forms

Use the individual if you're contributing as an individual and the corporate if you're contributing as part of funded work by some organization. You can email that to christopher.a.teubert@nasa.gov

Once you've done that you can open a PR in this repo (ProgPy), branching off of dev. At that point we will provide any review comments on your contributions. 

Thanks again for your contributions.

**Comment by teubert** [comment]
Resolved by @Ashwani132003. Thank you @Ashwani132003  for your help
